version: '2'
services:
  nrlsdemoapp:
    container_name: nrlsdemoapp
    image: nrlsdemo
    ports:
      - "8130:5000"
    networks:
      - nrlsdemo-network

  nrlsapiapp:
    container_name: nrlsapiapp
    image: nrlsapi
    ports:
      - "8101:5001"
    networks:
      - nrlsdemo-network

  nrlsmongodb:
    container_name: nrlsmongodb
    image: nrlsmongodb
    networks:
      - nrlsdemo-network

networks:
  nrlsdemo-network:
    driver: bridge